#!/bin/bash
# Deploy WebMaker AI Frontend to Vercel
# This script guides through the deployment process

echo "==================================="
echo "WebMaker AI - Vercel Deployment"
echo "==================================="
echo ""
echo "Since the Vercel token requires CLI login,"
echo "here's the easiest way to deploy:"
echo ""
echo "METHOD 1: GitHub Integration (Recommended)"
echo "-------------------------------------------"
echo "1. Go to: https://vercel.com/new"
echo "2. Sign in with your GitHub account"
echo "3. Import repository: AEnldlya/webmaker-ai"
echo "4. Configure:"
echo "   - Framework: Next.js"
echo "   - Root Directory: frontend"
echo "   - Build Command: npm run build"
echo "   - Output Directory: .next"
echo "5. Add Environment Variable:"
echo "   - Name: NEXT_PUBLIC_API_URL"
echo "   - Value: http://localhost:3001"
echo "6. Click 'Deploy'"
echo ""
echo "Your site will be live at: https://webmaker-ai.vercel.app"
echo ""
echo "METHOD 2: Vercel CLI (Alternative)"
echo "-----------------------------------"
echo "1. Install Vercel CLI: npm i -g vercel"
echo "2. Login: vercel login"
echo "3. Go to frontend folder: cd frontend"
echo "4. Run: vercel --prod"
echo ""
echo "METHOD 3: Local Development"
echo "----------------------------"
echo "1. Start Docker: docker-compose up -d"
echo "2. Frontend: http://localhost:3000"
echo "3. Backend: http://localhost:3001"
echo ""
echo "==================================="
echo "Repository: https://github.com/AEnldlya/webmaker-ai"
echo "Status: Ready to deploy!"
echo "==================================="